# Generated by Django 2.1.5 on 2019-11-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_mere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('cat_mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.Categorie_mere')),
            ],
        ),
        migrations.CreateModel(
            name='Emballage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('taille', models.CharField(max_length=20)),
                ('hauteur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diametre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('desc_prod', models.TextField()),
                ('image_prod', models.ImageField(upload_to='image_producteur/')),
                ('adresse1', models.CharField(max_length=30)),
                ('adresse2', models.CharField(max_length=30, null=True)),
                ('code_p', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=20)),
                ('tel_prod', models.PositiveIntegerField()),
                ('email_prod', models.EmailField(max_length=254)),
                ('nom_contact', models.CharField(max_length=30)),
                ('prenom_contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prix_p', models.FloatField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement du produit")),
                ('date_der_modif', models.DateTimeField(auto_now=True, null=True, verbose_name='date de modification')),
                ('description', models.TextField(blank=True, null=True)),
                ('origine', models.CharField(max_length=30)),
                ('ingredient', models.TextField(default='à remplir')),
                ('conservation', models.TextField(blank=True, null=True)),
                ('conseil_prepa', models.TextField(blank=True, null=True)),
                ('energie_kj', models.PositiveIntegerField(blank=True, null=True)),
                ('energie_kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('matiere_grasse', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('acide_gras_sat', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('glucide', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sucres', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fibre_alim', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('proteine', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sel', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image_p', models.ImageField(upload_to='image_produit/')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.Categorie_produit')),
                ('producteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.Producteur')),
            ],
            options={
                'verbose_name': 'produit',
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='Type_de_prix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='type_prix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.Type_de_prix'),
        ),
    ]
