# Generated by Django 2.1.5 on 2019-11-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='adresse1',
            field=models.CharField(max_length=30, verbose_name='Adresse n°1'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='adresse2',
            field=models.CharField(max_length=30, null=True, verbose_name='Adresse n°2, facultative'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='code_p',
            field=models.PositiveIntegerField(verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='desc_prod',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='email_prod',
            field=models.EmailField(max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='image_prod',
            field=models.ImageField(upload_to='image_producteur/', verbose_name='Image du producteur'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nom du producteur'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom_contact',
            field=models.CharField(max_length=30, verbose_name='Nom du contact'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='prenom_contact',
            field=models.CharField(max_length=30, verbose_name='Prénom du contact'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='tel_prod',
            field=models.PositiveIntegerField(verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='ville',
            field=models.CharField(max_length=20, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='acide_gras_sat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Acides gras saturés'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='conseil_prepa',
            field=models.TextField(blank=True, null=True, verbose_name='Conseil de préparation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='conservation',
            field=models.TextField(blank=True, null=True, verbose_name='Conseil de conservation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date d'enregistrement du produit"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='energie_kcal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Valeur Energétique en Kcal'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='energie_kj',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Valeur Energétique en Kj'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fibre_alim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Fibres alimentaires'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='glucide',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Glucides'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_p',
            field=models.ImageField(upload_to='image_produit/', verbose_name='Image du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='ingredient',
            field=models.TextField(default='à remplir', verbose_name='Ingrédient'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='matiere_grasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Matières grasses'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=40, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='origine',
            field=models.CharField(max_length=30, verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_p',
            field=models.FloatField(blank=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='proteine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Protéines'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Sel'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sucres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='dont sucres'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_prix',
            field=models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('u', 'U')], default='kg', max_length=3, verbose_name='Type du prix'),
        ),
    ]
