# Generated by Django 2.1.5 on 2019-11-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_auto_20191129_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type_de_prix',
        ),
    ]
