# Generated by Django 2.1.3 on 2018-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_auto_20181130_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_p',
            field=models.FloatField(blank=True),
        ),
    ]
