# Generated by Django 2.1.5 on 2019-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_delete_type_de_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='adresse1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Adresse n°1'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='adresse2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Adresse n°2, facultative'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='code_p',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='desc_prod',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='email_prod',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='image_prod',
            field=models.ImageField(blank=True, null=True, upload_to='image_producteur/', verbose_name='Image du producteur'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom_contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom du contact'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='prenom_contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prénom du contact'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='tel_prod',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='ville',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_p',
            field=models.ImageField(blank=True, null=True, upload_to='image_produit/', verbose_name='Image du produit'),
        ),
    ]
