# Generated by Django 2.1.3 on 2018-12-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_auto_20181227_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='valeurs_nutri',
        ),
        migrations.DeleteModel(
            name='Valeurs_nutritionnelles',
        ),
    ]
