# Generated by Django 2.1.3 on 2019-01-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_auto_20181227_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='sel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
