# Generated by Django 2.1.5 on 2019-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_auto_20191129_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emballage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boutique/image_vente/', verbose_name="Image de l'emballage"),
        ),
    ]
