# Generated by Django 2.1.3 on 2019-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_auto_20190103_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='proteine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
