# Generated by Django 2.1.5 on 2019-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_remove_emballage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emballage',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='prixunite',
            name='unite',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
