# Generated by Django 2.1.5 on 2019-12-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='prix',
        ),
    ]
