# Generated by Django 2.1.5 on 2019-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_emballage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_mere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='categorie_produit',
            name='cat_mere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.Categorie_mere'),
        ),
    ]
