# Generated by Django 2.1.5 on 2019-02-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_auto_20190226_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie_produit',
            name='cat_mere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.Categorie_mere'),
        ),
    ]
