# Generated by Django 2.1.5 on 2019-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_remove_panier_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='nb',
            field=models.IntegerField(default=1, verbose_name="Nombre d'article"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quantité du produit'),
        ),
    ]
