# Generated by Django 2.1.5 on 2019-10-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0013_auto_20190226_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_saisie'], 'verbose_name': 'produit'},
        ),
    ]
