# Generated by Django 2.1.5 on 2019-11-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecustomer',
            name='newsletter',
        ),
    ]
