# Generated by Django 2.1.5 on 2019-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profilecustomer_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecustomer',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
