# Generated by Django 2.1.5 on 2019-10-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adress',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post_code',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
