# Generated by Django 2.1.5 on 2019-10-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191015_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='téléphone'),
        ),
    ]
