# Generated by Django 2.1.5 on 2019-10-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191015_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adress',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='code postal'),
        ),
    ]
