# Generated by Django 2.1.5 on 2019-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191023_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
