# Generated by Django 2.1.5 on 2019-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_myuser_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='other_info',
            field=models.CharField(blank=True, max_length=30, verbose_name='informations complémentaires'),
        ),
    ]
