# Generated by Django 2.1.5 on 2019-10-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191028_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adress',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ville'),
        ),
    ]
