# Generated by Django 2.1.5 on 2019-11-06 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191028_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=30, verbose_name='prénom')),
                ('societe', models.CharField(blank=True, max_length=30, verbose_name="nom de l'entreprise")),
                ('phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='téléphone')),
                ('numetvoie', models.CharField(blank=True, max_length=50, null=True, verbose_name='numéro et nom de la rue')),
                ('post_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='ville')),
                ('other_info', models.CharField(blank=True, max_length=50, verbose_name='informations complémentaires')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='post_code',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
