# Generated by Django 2.1.5 on 2019-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191119_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
    ]
