# Generated by Django 2.1.5 on 2019-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191119_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='address',
            name='numetvoie',
            field=models.CharField(max_length=50, verbose_name='numéro et nom de la rue'),
        ),
        migrations.AlterField(
            model_name='address',
            name='other_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='informations complémentaires'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.PositiveIntegerField(verbose_name='code postal'),
        ),
        migrations.AlterField(
            model_name='address',
            name='prenom',
            field=models.CharField(max_length=30, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='address',
            name='societe',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="nom de l'entreprise"),
        ),
    ]
