# Generated by Django 2.1.5 on 2019-11-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_myuser_adresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='adresses',
        ),
        migrations.AddField(
            model_name='myuser',
            name='adresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Address'),
        ),
    ]
