# Generated by Django 2.1.5 on 2019-11-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191120_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adresses',
            field=models.ForeignKey(limit_choices_to={'user': models.EmailField(max_length=254, unique=True, verbose_name='E-mail')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Address'),
        ),
    ]
