# Generated by Django 2.1.3 on 2018-11-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('origine', models.CharField(max_length=30)),
                ('ingredient', models.TextField()),
                ('conservation', models.TextField()),
                ('conseil_prepa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('desc_prod', models.TextField()),
                ('image_prod', models.ImageField(upload_to='image_producteur/')),
                ('adresse1', models.CharField(max_length=30)),
                ('adresse2', models.CharField(max_length=30, null=True)),
                ('code_p', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=20)),
                ('tel_prod', models.PositiveIntegerField()),
                ('email_prod', models.EmailField(max_length=254)),
                ('nom_contact', models.CharField(max_length=30)),
                ('prenom_contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type_de_prix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Valeurs_nutritionnelles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie_kj', models.PositiveIntegerField()),
                ('energie_kcal', models.PositiveIntegerField()),
                ('matiere_grasse', models.PositiveIntegerField()),
                ('acide_gras_sat', models.PositiveIntegerField()),
                ('glucide', models.PositiveIntegerField()),
                ('sucres', models.PositiveIntegerField()),
                ('fibre_alim', models.PositiveIntegerField()),
                ('proteine', models.PositiveIntegerField()),
                ('sel', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='image_produit',
            new_name='image_p',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix_produit',
            new_name='prix_p',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nom_du_produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='type_du_prix',
        ),
        migrations.AddField(
            model_name='produit',
            name='date_der_modif',
            field=models.DateTimeField(null=True, verbose_name='date de modification'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique.Categorie_produit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='desc_p',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique.Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='producteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique.Producteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='type_prix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique.Type_de_prix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='valeurs_nutri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique.Valeurs_nutritionnelles'),
            preserve_default=False,
        ),
    ]
