# Generated by Django 2.1.3 on 2018-12-26 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_auto_20181226_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_saisie',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement du produit"),
        ),
    ]
