# Generated by Django 2.1.3 on 2018-12-27 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_auto_20181226_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='desc_p',
        ),
        migrations.AddField(
            model_name='produit',
            name='acide_gras_sat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='conseil_prepa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='conservation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='energie_kcal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='energie_kj',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='fibre_alim',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='glucide',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='ingredient',
            field=models.TextField(default='à remplir'),
        ),
        migrations.AddField(
            model_name='produit',
            name='matiere_grasse',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='origine',
            field=models.CharField(default='eref', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='proteine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='sel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='sucres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_der_modif',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de modification'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_saisie',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement du produit"),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
