# Generated by Django 2.1.3 on 2019-02-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_auto_20190103_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emballage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('taille', models.CharField(max_length=20)),
                ('hauteur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diametre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
